services:
  database:
    image: timescale/timescaledb:latest-pg17
    ports:
      - "54322:5432"
    env_file:
      - db.env
    volumes:
      - homeserver-db-data:/var/lib/postgresql/data
    networks:
      - homeserver-network

  kc-database:
    image: postgres:17.5-bookworm
    ports:
      - "54321:5431"
    env_file:
      - kc-db.env
    volumes:
      - homeserver-kc-db-data:/var/lib/postgresql/data
    networks:
      - homeserver-network

  broker:
    image: eclipse-mosquitto:2.0.21
    ports:
      - "1883:1883"
    volumes:
      - homeserver-broker-data:/mosquitto/data
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    networks:
      - homeserver-network

  liquibase:
    image: juhanir/liquibase-migrator:1.0.3
    depends_on:
      - database
    volumes:
      - ../homeserver-database/changelog:/liquibase/changelog
    env_file:
      - liquibase.env
    command: >
      bash -c "/wait-for-db.sh && liquibase --changeLogFile=db.changelog.xml update"
    networks:
      - homeserver-network

  keycloak:
    image: juhanir/homeserver-keycloak:1.0.1
    depends_on:
      - kc-database
    ports:
      - "8888:8888"
    volumes:
      - ./homeserver-realm-dev.json:/opt/keycloak/data/import/realm-import.json
    env_file:
      - keycloak.env
    command: start --verbose --import-realm --optimized
    networks:
      - homeserver-network
    healthcheck:
      test: ["CMD-SHELL", "{ printf 'HEAD /health/ready HTTP/1.0\r\n\r\n' >&0; grep 'HTTP/1.0 200'; } 0<>/dev/tcp/localhost/9000"]
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 10s

volumes:
  homeserver-db-data:
  homeserver-kc-db-data:
  homeserver-broker-data:

networks:
  homeserver-network:
    driver: bridge
