name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: 'x64'
          cache: maven

      - name: Create db env file
        working-directory: ./docker
        run: |
          cat << EOF >> db.env
          POSTGRES_USER=verysecretuser
          POSTGRES_PASSWORD=verysecretpassword
          POSTGRES_DB=homeserver
          EOF

      - name: Create liquibase env file
        working-directory: ./docker
        run: |
          cat << EOF >> liquibase.env
          LIQUIBASE_COMMAND_URL=jdbc:postgresql://database:5432/homeserver
          LIQUIBASE_CLASSPATH=/liquibase/changelog
          LIQUIBASE_COMMAND_USERNAME=verysecretuser
          LIQUIBASE_COMMAND_PASSWORD=verysecretpassword
          HOST=database
          EOF

      - name: Create keycloak db env file
        working-directory: ./docker
        run: |
          cat << EOF >> kc-db.env
          POSTGRES_DB=keycloak
          POSTGRES_PASSWORD=verysecretpassword
          POSTGRES_USER=verysecretuser
          PGPORT=5431
          EOF

      - name: Create keycloak env file
        working-directory: ./docker
        run: |
          cat << EOF >> keycloak.env
          KC_DB=postgres
          KC_HOSTNAME=localhost
          KC_DB_URL=jdbc:postgresql://kc-database:5431/keycloak
          KC_DB_USERNAME=verysecretuser
          KC_DB_PASSWORD=verysecretpassword
          KC_BOOTSTRAP_ADMIN_USERNAME=verysecretuser
          KC_BOOTSTRAP_ADMIN_PASSWORD=verysecretpassword
          EOF

      - name: Run tests
        run: mvn --projects message-server --also-make clean test
