name: Homeserver build and test pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: 'x64'
          cache: maven

      - name: Create db env file
        working-directory: ./docker
        run: |
          cat << EOF >> db.env
          POSTGRES_USER=${{ secrets.VERY_SECRET_USER }}
          POSTGRES_PASSWORD=${{ secrets.VERY_SECRET_PW }}
          POSTGRES_DB=homeserver
          EOF

      - name: Create liquibase env file
        working-directory: ./docker
        run: |
          cat << EOF >> liquibase.env
          LIQUIBASE_COMMAND_URL=jdbc:postgresql://database:5432/homeserver
          LIQUIBASE_CLASSPATH=/liquibase/changelog
          LIQUIBASE_COMMAND_USERNAME=${{ secrets.VERY_SECRET_USER }}
          LIQUIBASE_COMMAND_PASSWORD=${{ secrets.VERY_SECRET_PW }}
          HOST=database
          EOF

      - name: Create keycloak db env file
        working-directory: ./docker
        run: |
          cat << EOF >> kc-db.env
          POSTGRES_DB=keycloak
          POSTGRES_USER=${{ secrets.VERY_SECRET_USER }}
          POSTGRES_PASSWORD=${{ secrets.VERY_SECRET_PW }}
          PGPORT=5431
          EOF

      - name: Create keycloak env file
        working-directory: ./docker
        run: |
          cat << EOF >> keycloak.env
          KC_DB=postgres
          KC_HOSTNAME=localhost
          KC_DB_URL=jdbc:postgresql://kc-database:5431/keycloak
          KC_DB_USERNAME=${{ secrets.VERY_SECRET_USER }}
          KC_DB_PASSWORD=${{ secrets.VERY_SECRET_PW }}
          KC_BOOTSTRAP_ADMIN_USERNAME=${{ secrets.VERY_SECRET_USER }}
          KC_BOOTSTRAP_ADMIN_PASSWORD=${{ secrets.VERY_SECRET_PW }}
          KC_HTTP_MANAGEMENT_SCHEME=http
          KC_HTTP_PORT=8888
          KC_HTTP_ENABLED=true
          EOF

      - name: Run tests
        run: mvn -B -q --projects message-server --also-make clean test

      - name: Set up Node.js 22
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'
          architecture: 'x64'
          package-manager-cache: true

      - name: Create frontend env file
        working-directory: ./homeserver-ui
        run: |
          cat << EOF >> .env
          VITE_KEYCLOAK_URL=
          VITE_KEYCLOAK_REALM=
          VITE_KEYCLOAK_CLIENT_ID=
          VITE_MESSAGE_SERVER_API_URL=
          EOF

      - name: Install dependencies
        working-directory: ./homeserver-ui
        run: npm ci

      - name: Build
        working-directory: ./homeserver-ui
        run: npm run build

      - name: Run frontend tests
        working-directory: ./homeserver-ui
        run: npm run test
